# Generated by Django 4.2.2 on 2024-08-28 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(default="2000-01-01", verbose_name="Дата рождения"),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_at",
            field=models.DateField(
                auto_now_add=True, verbose_name="Дата редактирования"
            ),
        ),
    ]
